[kafka]
brokers = "kafka:9092"

[[chains]]
rpc_url = "wss://holesky.infura.io/ws/v3/8dd4a35393c04ed8a4c1c563c8ea099e"
contract_address = "0x92ab20b794f35Ff9A0d1AD0D19f8fB42F460Ae3D" 
event_name = "MessageEvent(string)"
kafka_topic = "KAFKA_TOPIC_1"

[[chains]]
rpc_url = "wss://linea-sepolia.infura.io/ws/v3/8dd4a35393c04ed8a4c1c563c8ea099e"
contract_address = "0xB0dE0169FaC706B2545b8B03E0aAf4Df9B699bc5" 
event_name = "MessageEvent(string)"
kafka_topic = "KAFKA_TOPIC_1"

[[chains]]
rpc_url = "wss://holesky.infura.io/ws/v3/8dd4a35393c04ed8a4c1c563c8ea099e"
contract_address = "0x92ab20b794f35Ff9A0d1AD0D19f8fB42F460Ae3D" 
event_name = "NumberEvent"
kafka_topic = "KAFKA_TOPIC_2"